apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- if eq .Values.target "local" }}
        command: ["/bin/sh", "-c", "sleep 1000"]
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: ADDR
          value: ":{{ .Values.service.port }}"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: database-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: database-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: database-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: database-name
        imagePullPolicy: {{ .Values.image.pullPolicy }}
