{{- if eq .Values.target "eks" }}
{{- if or .Values.secrets.databaseUser .Values.secrets.databasePassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  {{- if .Values.secrets.databaseUser }}
  database-user: {{ .Values.secrets.databaseUser | b64enc }}
  {{- end }}
  {{- if .Values.secrets.databasePassword }}
  database-password: {{ .Values.secrets.databasePassword | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
